/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'sweeteners' : IDL.Null,
  'leaveningAgents' : IDL.Null,
  'fatsOils' : IDL.Null,
  'decoratingTools' : IDL.Null,
  'bakingEquipment' : IDL.Null,
  'cakeMixes' : IDL.Null,
  'floursGrains' : IDL.Null,
  'flavorExtracts' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'pricePaise' : IDL.Nat,
  'description' : IDL.Text,
  'category' : ProductCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Time = IDL.Int;
export const DeliveryOption = IDL.Variant({
  'express' : IDL.Null,
  'standard' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'pricePaise' : IDL.Nat,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'deliveryOption' : DeliveryOption,
  'items' : IDL.Vec(OrderItem),
  'paymentIntentId' : IDL.Text,
  'totalAmountPaise' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'filterProducts' : IDL.Func(
      [
        IDL.Opt(ProductCategory),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidPincode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [DeliveryAddress, DeliveryOption, IDL.Text],
      [IDL.Text],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedProducts' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'sweeteners' : IDL.Null,
    'leaveningAgents' : IDL.Null,
    'fatsOils' : IDL.Null,
    'decoratingTools' : IDL.Null,
    'bakingEquipment' : IDL.Null,
    'cakeMixes' : IDL.Null,
    'floursGrains' : IDL.Null,
    'flavorExtracts' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'pricePaise' : IDL.Nat,
    'description' : IDL.Text,
    'category' : ProductCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Time = IDL.Int;
  const DeliveryOption = IDL.Variant({
    'express' : IDL.Null,
    'standard' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'pricePaise' : IDL.Nat,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'deliveryOption' : DeliveryOption,
    'items' : IDL.Vec(OrderItem),
    'paymentIntentId' : IDL.Text,
    'totalAmountPaise' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'filterProducts' : IDL.Func(
        [
          IDL.Opt(ProductCategory),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidPincode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [DeliveryAddress, DeliveryOption, IDL.Text],
        [IDL.Text],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedProducts' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };